name = "atc-tefl-landing"
compatibility_date = "2026-09-24"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "atc-tefl-leads"
database_id = "6c7de133-d61c-49cd-8878-17e975d1ea75"
