name = "atc-tefl-landing"
main = "src/worker.js"
compatibility_date = "2026-09-24"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "atc-tefl-leads"
database_id = "6c7de133-d61c-49cd-8878-17e975d1ea75"
